### ISSUE TITLE
Create build script

### ISSUE THREAD

**Issue by remcohaszing** [itslanguage/itslanguage-js#137]
By introducing ES6 imports / exports, the code doesn't simply run as-is anymore. Version `0.2.0` can only be used when transpiled at runtime. This can be a choice, but is mostly unwanted and unexpected behaviour.

The code should be transpiled using babel before publishing to npm.

I think it makes sense to move the code into a `src` directory and output the build in a gitignored `build` directory. This will require some customization in the release process.

**Comment by Lehren** [comment]
Everything's in a `src` directory now. Could someone change the build process to output into a `build` directory?

**Comment by Lehren** [comment]
bump @remcohaszing
