### ISSUE TITLE
Travis publishes entire directory to npm

### ISSUE THREAD

**Issue by Lehren** [itslanguage/itslanguage-js#168]
Travis should only deploy the generated `build` directory. 

Apparently the `local_dir` tag in .travis.yml does not work.

**Comment by Lehren** [comment]
https://github.com/itslanguage/itslanguage-js/pull/169 Didn't fix it.

**Comment by joggienl** [comment]
out dated, the current deploy process is capable to deploy just enough and nothing more :-)
