### ISSUE TITLE
Fix all eslint-disable comments

### ISSUE THREAD

**Issue by remcohaszing** [itslanguage/itslanguage-js#20]
Most, if not all, `eslint-disable` comments actually exist for no good reason. They should be removed and the real errors should be fixed.

This includes the rules disabled in `.eslintrc`.

**Comment by Lehren** [comment]
> Most, if not all

Are there any reasons why `eslint-disable` should be allowed in a file?

**Comment by remcohaszing** [comment]
> Are there any reasons why eslint-disable should be allowed in a file?

Yes, when a REST API or JavaScript library requires snake_case properties as input.
