### ISSUE TITLE
Change 'listX' methods to 'getX' or 'getAllX'

### ISSUE THREAD

**Issue by Lehren** [itslanguage/itslanguage-js#232]
It's more conventional this way.

**Comment by joggienl** [comment]
The plan is to refactor all listX methods to getXs methods.

```js
// before:

/**
 * List all users
 */
function listUsers() { ... }

// after:

/*
 * Get and return all users
 */
function getUsers() { ... }
```

Major breaking change. I would like to suggest to keep the listX functions before removing them (for compatibility). We should mark them as deprecated.

This would be nice to have in the 2.x release (with the listX methods deprecated) and remove support in the next major release.

**Comment by kvdb** [comment]
Since we're currently our only users of the SDK, breakage is still fine with me. Obviously, we'll be be careful with our semver breakage when it's really needed. Let's not complicate matters now, if it's a simple refactor for @joggienl and it's really 'conventional wisdom', i'd say it's ok for now.
However, a link to backup this conventional wisdom would be nice, because I didn't know that.

**Comment by joggienl** [comment]
I probably would not say "conventional" but rather "consistent". As example, fetching one user can be done by `getUser(x)`. So getting all users I would more naturally expect `getUsers` or `getAllUsers` instead of `listUsers`.

**Comment by joggienl** [comment]
And I would still opt for the deprecating way if we want to introduce this in a minor release. For a major we could supply a "migration guide" (should be minor effort I guess).

**Comment by Lehren** [comment]
Deprecate the methods or not? Next release is going to be major anyway and since we are the only users I don't see the point in keeping the old methods.

**Comment by joggienl** [comment]
If this can be in the next major, then breaking is OK. We need to provide some sort of migration guide then!

"we are the only users" is not valid imho.
