### ISSUE TITLE
Remove logging

### ISSUE THREAD

**Issue by remcohaszing** [itslanguage/itslanguage-js#249]
This project has very verbose logging and there's no way to disable this. This spams the console rendering it pretty much useless, especially when recording.

A configurable logger could be used. However, I think it would be best to simply remove all console calls.

**Comment by joggienl** [comment]
I would opt for configurable logging

**Comment by kvdb** [comment]
Yep, a client also expressed this wish.

**Comment by joggienl** [comment]
putting it back on my list!

**Comment by joggienl** [comment]
closed due to v4.0.0 release.
