### ISSUE TITLE
Remove getUserMedia checks

### ISSUE THREAD

**Issue by remcohaszing** [itslanguage/itslanguage-js#250]
I suggest to remove any checks regarding the existence of any form of `getUserMedia` and just assume that `navigator.mediaDevices.getUserMedia` is available.

There is a polyfill available for this ([md-gum-polyfill][md-gum-polyfill]).

The SDK should **not** depend on this polyfill. It might recommend it in the readme.

[md-gum-polyfill]: https://www.npmjs.com/package/md-gum-polyfill

**Comment by kvdb** [comment]
Why should we just assume that? You can be sure IE9 users try our SDK.

**Comment by joggienl** [comment]
The project using the SDK could provide a polyfill for its users.

**Comment by kvdb** [comment]
Agreed. This issue became relevant again since the refactor of the deprecated navigator.getUserMedia is probably what needs to be done to get the SDK to work on iOS Safari (currently beta).

**Comment by joggienl** [comment]
closed due to v4.0.0 release.
