### ISSUE TITLE
Replace when.Promise

### ISSUE THREAD

**Issue by remcohaszing** [itslanguage/itslanguage-js#261]
Autobahn and itslanguage both heavily rely on `when.Promise`. This is a promise implementation that implements a custom `progress` function. This never made it into the now established `Promise` spec. It is awkward to use a library that enforces this use.

Some alternatives that came to my mind are:

- [Generators][generators] — I haven't used them yet and would have to dive into this, but they might just do the trick.
- [RxJS][rxjs] — This is a popular library that handles asynchronous stuff. Typically this handles stuff that requires a success, error and progress handler.

[generators]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator
[rxjs]: http://reactivex.io

**Comment by joggienl** [comment]
Autobahn still uses it (they are not planning to remove it).
Our SDK needs to be aware of this because "progressed events" need to be sent to the server or received from the server. The SDK only uses the when.promise in this situation. All other places uses vanilla Promises.
