### ISSUE TITLE
SDK user should be able to catch the getusermedia exception.

### ISSUE THREAD

**Issue by kvdb** [itslanguage/itslanguage-js#281]
When the user requests getusermedia permission and user says: no, the user of the SDK should be able to catch this error and act upon it (i.e. show a warning to the student). Currently, it can't be caught by wrapping the sdk call in a try/catch. It might be good to show the use in the example project too.
Don't catch the error in a promise, just make the code there simpler.

**Comment by joggienl** [comment]
Only thing the SDK can and should do is, make it possible to check for user permission. Something like: `recorder.gavePermission();` which returns either true or false. We can (and maybe should) add a message to the console as well (as part of the debug information btw, we should not randomly spam here).

Displaying anything like a message to the _end user_ should be the responsibility of the app using the SDK. We should not try to implement that (here).

**Comment by joggienl** [comment]
closed due to v4.0.0 release.
