### ISSUE TITLE
SDK should allow to insert a token to use.

### ISSUE THREAD

**Issue by kvdb** [itslanguage/itslanguage-js#282]
A client fetches the student token in the backend. The backend renders the html page and wants to insert the token at that time. So, next to this call:
getCurrentUser(): Promise<User>
It'd be useful to have a setCurrentToken() or setCurrentUser().

**Comment by mthjs** [comment]
``Connection.addAccessToken();``

**Comment by mthjs** [comment]
I'm keen on closing this; but I think documentation is still lacking. I'll update #293 so it'll declare that during the refactor documentation needs to be extended and improved

**Comment by joggienl** [comment]
it is possible to use the SDK and construct it with an access token:

```js
import { createItslSdk } from '@itslanguage/sdk';

const config = {
  apiUrl: 'api-url-here',
  wsUrl: 'ws-url-here',
  authorizationToken: 'put-the-token-here',
};

// Use the config object. No need to authenticate afterwards,
// the token will be used for communication with the backend.
const sdk = createItslSdk(config);
```

Currently this is only available on the `next` branch (version 4 to be). This will soon be stable released.
