### ISSUE TITLE
Work in Progress

### ISSUE THREAD

**Issue by mthjs** [itslanguage/itslanguage-js#293]
This issue is merely to keep track of things that still need to be taken care of in the refactoring. 

Working hard to refactor all the components into something more readable, maintainable, and usable. Here follows a list of things which need to be taken care of.

- [x] Communication mechanism
  - [x] Single set of settings for both the WS and GAE communication
  - [x] Allows to make both authorized and unauthorized requests.
  - [x] Exposes the WebSocket communication mechanism through a submodule.
  - [x] Inject authorisation token into download GET URLs
- [x] Authentication mechanism using the new ITS-GAE communication mechanism
  - [x] Request Authorization token
  - [x] Create Email Auth
  - [x] Create Basic Auth
- [x] Make the APIs use the new communication mechanism
  - [x] Organisations
  - [x] Groups
  - [x] Users
  - [x] Roles
  - [x] Categories
  - [x] Challenges
    - [x] Choice
    - [x] Speech
    - [x] Pronunciation
  - [x] Recordings
    - [x] Choice
    - [x] Pronunciation
    - [x] Speech
- [ ] Write extensive documentation
  - [ ] Declare what a developer needs to do when they want to contribute
  - [ ] Provide clear examples as to how to use the SDK
  - [ ] Provide a good troubleshooting guide
  - [ ] Provide a GitHub issue template

Something we also should keep in mind is the way we expect to receive the audio; currently we enforce the usage of our own `AudioRecorder`. This does, however, limit the way developers can obtain the data. It would be wise to revise this by looking into processing raw [`MediaStream`s][MDN MediaStream] using [`AudioContext`][MDN AudioContext] and [`AudioContext`'s][MDN AudioContext] methods: [`createMediaStreamSource()`][MDN AudioContext.createMediaStreamSource] and [`createScriptProcessor()`][MDN AudioContext.createScriptProcessor] to do the necessary preparation for ITS-WS.

[MDN MediaStream]: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream
[MDN AudioContext]: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext
[MDN AudioContext.createMediaStreamSource]: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamSource
[MDN AudioContext.createScriptProcessor]: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createScriptProcessor

**Comment by joggienl** [comment]
closed due to v4.0.0 release.
