### ISSUE TITLE
Add VolumeMeter package

### ISSUE THREAD

**Issue by joggienl** [itslanguage/itslanguage-js#326]
Add a new package that exposes a volume meter.
The output of this meter should be RMS value of some input (either audio or microphone).

Preferably this needs to be done by using an AnalyserNode but latest tests have shown that the function that exposes this info _do_ exist but don't work.

Workaround _could_ be using the ScriptProcessorNode (something like the `onaudioprocess` event) and or combine this with the `AnalyserNode`.

**Comment by kvdb** [comment]
I think you can close this one since you merged the AmplitudePlugin, right?

**Comment by joggienl** [comment]
Closing was correct.
References #341 and #335.
