### ISSUE TITLE
Use binary audio transfer instead of base64 encoding

### ISSUE THREAD

**Issue by kvdb** [itslanguage/itslanguage-js#44]
Please try out msgpack serialisation when submitting binary audio that's currently base64 encoded. This is less efficient. PR #43 reminded me of this.

It previously wasn't possible. See upstream:
https://github.com/crossbario/autobahn-js/issues/67

See also the notes on this subject in https://build.d-centralize.nl/redmine/issues/1475
The backend supports both forms already (base64 and binary), see https://build.d-centralize.nl/redmine/projects/its-ws-server/repository/revisions/fbea39762a514a70ce8cb028d26e1ecfde53e8a7/diff

**Comment by joggienl** [comment]
closing this issue sinse it is a little out dated imo.
