### ISSUE TITLE
Use event emitters

### ISSUE THREAD

**Issue by remcohaszing** [itslanguage/itslanguage-js#66]
Currently the SDK uses custom implementations of `addEventListener` and `removeEventListener`.

It's probably better to use more standarized event emitters ([Events](https://nodejs.org/api/events.html)). There's a popular port for browsers as well ([event-emitter](https://www.npmjs.com/package/event-emitter)).

**Comment by Lehren** [comment]
Does this need discussion or approval? I'd do it but I guess I'm waiting for a discussion...

**Comment by kvdb** [comment]
I'm all for using better standards than those custom implementations I made.
